## Backup Running Config 
 
- hosts: all 
 
  tasks:
   - name: Backup Running Config 
     ios_command:
       commands: show running-config   
     register: config

   - name: Create a directory
     ansible.builtin.file:
        path: /home/dex/configurations
        state: directory
        mode: '0755'
     
   - name: Save output 
     copy:
       content: "{{config.stdout[0]}}"
       dest: "../configurations/{{ ansible_net_hostname }}-config.txt"


   - name: Save running config
     ios_config:
        save_when: always 
