---

- name: FTP Backup
  hosts: all
  vars:
    backup_base_path: "/home/ftp_dex"  
  gather_facts: true
  tasks:

    - name: chemin
      ansible.builtin.set_fact:
        backup_path: "{{ backup_base_path }}/{{ lookup('pipe', 'date +%F') }}"
    
    - name: Create the backup folder
      ansible.builtin.file:
        path: "{{ backup_path }}"
        state: directory
        mode: '0755'